### ISSUE TITLE
Veliki font u SMS aplikaciji

### ISSUE THREAD

**Issue by dakyst** [MASVA/MA-XML-7.0-CROATIAN-master#1]
Pozdrav MASVA!

Primjetio sam na da na Redmi 2 modelu HM2014811 kada je postavljena normalna veličina fonta, u SMS aplikaciji font je prevelik, dok je npr. kod Redmi 1S modela SMS font u skladu sa postavljenom veličinom. Oba uređaja koriste najnoviji update sa Xiaomi.eu MIUI 7 5.11.26. Ako je potrebno mogu preložiti screenshot.

Hvala ti unaprijed ako popraviš ovaj mali bug!

Pozdrav!

**Comment by MASVA** [comment]
imaš mogućnost promjene veličine fonta u Postavke --> Veličina teksta
nabaci koji screenshot da vidim pa probam nešto iskemijati
lp

**Comment by dakyst** [comment]
![redmi 2](https://cloud.githubusercontent.com/assets/12613976/11471559/e6547e3e-9766-11e5-9013-b3a6ec1478e7.jpg)
![redmi 1s](https://cloud.githubusercontent.com/assets/12613976/11471560/e665734c-9766-11e5-9b64-47a8117950f7.jpg)

Dada znam za promjene postavki, ali kad je na postavljeno na Normalni font, tj. S veličinu, font u SMS-u na Redmi-u 2 je ogroman. Evo baci oko na slike što sam ti uploadao. Prvi screenshot je Redmi 2, a drugi je Redmi 1S. Slike su iste veličine i nista nisam zumirao ni povećavao.

Nekada se zna popraviti samo od sebe kada se resetira tema ili promijeni jezik, ali nakon nekog vremena opet se vrati samo od sebe na velika slova.

Već sam bio napisao ovaj bug na forum xiaomi.eu, ali me nitko nije obadavao pa sad neznam jel to problem do Hrvatskog jezika ili je nekakav bug u ROM-u.

**Comment by MASVA** [comment]
našao rješenje
u petak bude popravljeno
lp

**Comment by dakyst** [comment]
Ala super! Javim ti nakon updatea jel uspjelo!

**Comment by dakyst** [comment]
Novi update je popravio font! Svaka čast! Hvala puno!

**Comment by MASVA** [comment]
ok, drago mi je da je riješeno, zatvaram
lp
