### ISSUE TITLE
Nepreveden tekst na nekim mjestima

### ISSUE THREAD

**Issue by dakyst** [MASVA/MA-XML-7.0-CROATIAN-master#3]
Pozdrav Masva!

Primijetio sam da nakon ažuriranja na 6.3.3 (Redmi 1S) na par mjesta se pojavljuje engleski tekst, što se na prijašnjim ažuriranjima nije događalo. Npr. prilikom unošenja PIN-a na vrhu statusne trake piše: "Emergency calls only", dok je na prošlim ažuriranjima taj tekst bio na hrvatskom jeziku. Priložio sam screenshot sa dva primjera, ali nisam siguran ima li ih još.

![screen](https://cloud.githubusercontent.com/assets/12613976/13618282/954a40d0-e583-11e5-91a0-9dadd64d491e.jpg)

Unaprijed hvala!

**Comment by MASVA** [comment]
i kod mene na mi4c
radimo na otklanjanju problema....
lp

**Comment by dakyst** [comment]
Evo novi update je riješio stvar! Hvala lijepa!

Do sljedećeg bug-a (nadamo se da ih neće biti :D ) čujemo se!

Pozdrav

**Comment by MASVA** [comment]
nema frke
lp
