### ISSUE TITLE
music player hermes_v7.2.1.0

### ISSUE THREAD

**Issue by antimaterija70** [MASVA/MA-XML-7.0-CROATIAN-master#5]
Music player (glazba) ne radi kada je uključen hrvatski jezik.
Kada prebacim na engleski jezik radi bez greške.
![screenshot_2016-03-12-13-49-02_com miui home](https://cloud.githubusercontent.com/assets/17798123/13723087/fd5b21d4-e859-11e5-8764-70102aab4ac8.png)

**Comment by MASVA** [comment]
probaj ići u postavke-instalirane aplikacije-glazba-izbriši podatke

ako to neće uspjeti onda skini 6.3.10 za hermesa, raspakiraj aplikaciju i
root explorerom je zamijeni(trebaš root za to)
meni na mi4c 6.3.10 radi glazba bez problema

Dana 12. ožujka 2016. u 13:55 antimaterija70 notifications@github.com je
napisao/la:

**Comment by antimaterija70** [comment]
Izbrisao podatke - ne radi
Zamijenio sa verzijom iz 6.3.11 za hermesa  - ne radi
Zamijenio sa verijom iz 7.1.3.0 za hermesa - radi

2016-03-12 13:59 GMT+01:00 MASVA notifications@github.com:

**Comment by MASVA** [comment]
pronašao grešku
ispravljeno
https://drive.google.com/file/d/0B0XXQYHSxGEwNUJhZzk5WFF2b3JvYkZaUTJGM1lSbFdsdjQ4/view?usp=sharing
frend testirao na hermesu, clear data potreban
