### ISSUE TITLE
NetworkAssistant2.apk

### ISSUE THREAD

**Issue by usnkreal** [MASVA/MA-XML-7.0-CROATIAN-master#6]
NetworkAssistant2.apk/res/layout-hr/network_speed_view.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/number').
NetworkAssistant2.apk/res/layout-hr/network_speed_view.xml:5: error: Error: No resource found that matches the given name (at 'layout_toRightOf' with value '@id/number').
NetworkAssistant2.apk/res/layout-hr/network_speed_view.xml:5: error: Error: No resource found that matches the given name (at 'layout_alignTop' with value '@id/number').
NetworkAssistant2.apk/res/layout-hr/network_speed_view.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/unit').

**Comment by MASVA** [comment]
fino si ti to postao log
još da veliš koji mob i rom je u pitanju jer nisam vidovit?
ja te greške nemam na mi 5
probaj napraviti clear data za NetworkAssistant2

**Comment by usnkreal** [comment]
https://www.dropbox.com/s/nx1oetrd48zlwz3/error-layout.txt?dl=0

**Comment by MASVA** [comment]
ček malo, zašto ti meni šalješ compile log pogreške za jbart ?
kakve to ima veze s prijevodom?
